# Generated by Django 2.1 on 2018-09-26 11:35

import datetime
from django.db import migrations
from django.utils.timezone import utc
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0005_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='location',
            field=places.fields.PlacesField(default=datetime.datetime(2018, 9, 26, 11, 35, 31, 209143, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
