# Generated by Django 2.1 on 2018-09-26 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0006_help_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='photo',
        ),
    ]
