# Generated by Django 2.1 on 2018-09-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0007_remove_help_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/'),
        ),
    ]
